### PR TITLE
init: research questions

### PR DESCRIPTION
**Pull request by mikeal**
I want to try something new this quarter.

I’ve got a bunch of open research questions bouncing around in my head that I weave into the work we do each quarter. This quarter I’m trying something new, actually writing them down! 😂

These aren’t assigned to anyone, and they won’t be. These aren’t OKR’s, they are things we should keep thinking about and find creative ways to poke at over time. Most relevant to what I’m trying to do by writing them down, we should regularly be syncing up about what we’ve learned and surfacing it either as notes carried over into the next quarter or as large note docs in the specs repo.

I’m pretty sure this is not a complete list of our open questions. Our team keeps so much of this in our heads that we take it for granted and it’s hard for me to really recall what they are, so please feel free to add more.

/cc @warpfork @rvagg @ribasushi @chafey @vmx

### CODE REVIEW

**Comment by rvagg** [comment]
OK, I guess. Feels pretty big to be putting into a quarter. Is this the kind of thing we'd recycle each quarter, editing to add/remove items? That'd probably be a good thing to do. Otherwise this just feels like another way to set ourselves up for having a list of things we _didn't_ do.

Also, sorted multi-block collections keep on gnawing on the back of my brain.

**Comment by mikeal** [comment]
> Is this the kind of thing we'd recycle each quarter, editing to add/remove items? That'd probably be a good thing to do

Exactly. The idea is, we check in on these every quarter and sync up on what we’ve learned and what any remaining questions might be.

**Comment by mikeal** [comment]
> Also, sorted multi-block collections keep on gnawing on the back of my brain.

Me too, but the reason I’m not in a rush to work on it is because every day I put into DagDB is another day I learn more about what we will need here. I just finished up the indexing engine with the initial property indexing just built on the `hamt` and it has been very educational. My list of requirements is a bit larger than it once was but it’s also much clearer to me what things need to be in the data structure and what you can built into it with what we already have.

**Comment by rvagg** [comment]
closing for archival

**Pull request closed without merging**
