### PR TITLE
wip: 2020 q1 OKR’s

### PR DESCRIPTION
**Pull request by mikeal**
Need to get OKR’s in for the rest of the quarter’s work.

Please edit and add @creationix @vmx @rvagg @warpfork

### CODE REVIEW

**Comment by rvagg** [comment]
have pushed a second CAR OKR; mine are pretty unambitious but I think I'd like to discuss how important these OKRs are at this current time.

**Comment by rvagg** [comment]
... just noticed that my pushes have failed but I wasn't paying attention previously.. @mikeal we need to expand access rights to this repo.

I have two commits so far: https://github.com/ipld/roadmap/compare/2020-q1-okr-init...rvagg:2020-q1-okr-init - I added a new one for docs but set it as 0.3 expected so it's mainly just a placeholder reminder that this should get done some time this year.

**Comment by vmx** [comment]
@mikeal What do you think about removing my "Rust IPLD is feature complete" from the list (as we also don't even have a definition what feature compleness means) and rather add something like "Rust CID and Rust Multihash are maintained and usable". With "maintained" I mean, PRs merged, existing forks incorporated.

**Comment by mikeal** [comment]
@vmx notice that the expected completion rate by the end of the quarter is only 30% - part of what I’d like to have by the end of the quarter is a definition of what “feature complete” might be considered ;) “maintained and usable” make it sound like feature work is done and we’re in maintenance mode, which isn’t the state of the stack right now as I understand it.

**Comment by rvagg** [comment]
pushed my changes, needs to be squashed when merging tho

**Comment by vmx** [comment]
@mikeal Then perhaps the KR is just "have a metric for feature complete"? Though I'm not sure if it's actually worth spending time spelling that out. Immediate needs change a lot, so even a roadmap doesn't make much sense. It's more of a "make progress on the implementation, we should evaluate after the quarter if there was any progress and if not ring the alarm bells" (which doesn't fit into the OKR model).

**Comment by mikeal** [comment]
> Immediate needs change a lot, so even a roadmap doesn't make much sense. It's more of a "make progress on the implementation, we should evaluate after the quarter if there was any progress and if not ring the alarm bells" (which doesn't fit into the OKR model).

yes, there’s not a great match between the way we need to do this and the ORK model which is why i’m relying on fuzzy language like “feature complete” ;)

**Pull request merged**
