### PR TITLE
[WIP] Q4 OKR’s

### PR DESCRIPTION
**Pull request by mikeal**
It’s about time for us to start thinking about what we want next quarter’s OKR’s to be.

### CODE REVIEW

**Comment by rvagg** [comment]
I would really like to make progress on sorted collections. It's going to get a 0 for this quarter but would like to get somewhere closer to a 0.4 or higher by EOY. At least an experiment!

I'd also like us to begin nibbling on something _big_, an experiment that pulls in a significant amount of the work we've been circling around for the last few months. Package management being the obvious space I think. Something that we can use to exercise our ideas and code in non-trivial ways.

**Comment by rvagg** [comment]
@mikeal I'd be happy if you want to add the same entry for the Go parser as for the JS parser, I'm trying to keep them in something like parity

**Comment by mikeal** [comment]
@rvagg, ok great, i’ll add it and assign to you

**Comment by vmx** [comment]
OKRs I could work on:

 - @mikeal and I talked about writing a report on how to pass on IPLD Data Model values between JS and WASM. After watching [the video](https://www.youtube.com/watch?v=Qn_4F3foB3Q) linked from https://hacks.mozilla.org/2019/08/webassembly-interface-types/ about WebAssembly Interface Types it's clear to me that this is the way to go. There's no point of building something ourselves, but rather building on top of that. So one OKR could be: Writing an exploration report on how we will pass IPLD Data Model values into WASM modules via Interface types
 - There's some work on IPLD related things at https://github.com/dvc94ch/rust-ipld which e.g. implemented DagCbor (but not the way I'm doing it with Serde). I'd like to have some time looking into those things to find overlap and ways to work together. I've no clue how to formulate this as OKR.
 - We already have some [Multiformats implementations in Rust](https://github.com/multiformats?utf8=%E2%9C%93&type=&language=rust). Again I'd like to go over those (and their open issues) and find out what is needed for rust-ipld.

**Comment by mikeal** [comment]
I’m gonna land these over the weekend.

@rvagg @vmx @warpfork I also need Q3 final scores from ya’ll.

**Pull request merged**
