### PR TITLE
[WIP] Q1 2019 OKR's

### PR DESCRIPTION
**Pull request by mikeal**
Time for 2019 OKR's :)

Let's talk about what we think we can complete next quarter.

@vmx @warpfork

### CODE REVIEW

**Comment by warpfork** [comment]
- I want go-ipld-prime to be ready for use, to the degree we can start pointing people to it instead of the current go-ipld-cbor.  I hope that's a "spring" goal.
- I want a workable demo of a schema system (limited to fairly simple and common concepts of sum types, product types, and recursive types (maps, lists)).  (I *don't* presume to finish: a DSL or its parser, HKTs, etc.)

Those are my goals for myself.  I think those are roughly doable in a quarter.  They're already started, and the number of unknown-unknowns has been dropping steadily.

**Comment by vmx** [comment]
- I'd like to finish the JS IPLD API stuff, getting all existing implementation ported to the new API
 - Spending some time on the JS APIs/implementations on the lower-level building blocks, mostly the multiformats. Some of it is unpractical/hard to use (which I discovered working on the new JS IPLD APIs). I'd like to get those cleaned up
 - And of course doing some basic GraphSync stuff. Mostly showing how to integrate things like that into the JS implmentation.

**Comment by vmx** [comment]
Do we have a plan on how to make our ideas into proper OKRs? So far (looking at my scores) I don't seem to be good at defining OKRs.

**Comment by mikeal** [comment]
@vmx I'm working on this over the next few days :)

**Comment by mikeal** [comment]
I created a new file with OKR's. Check them out @vmx and @warpfork.

@vmx, what is something we can accomplish this quarter to move forward on modularizing the replication efforts?

**Comment by vmx** [comment]
@mikeal I thought about something along the lines of: Prototype/demonstration that transfers files through something that is not Bitswap.

What I mean with it is that it won't be any better than Bitswap or work well. It might only work with two hard-coded peers. The goal is to show that the architecture/APIs are ready.

**Comment by mikeal** [comment]
Push some fixes:

* README improvement.
* @vmx I added a replication OKR.
* I added some unixfsv2 OKR's for myself.

**Review by vmx — APPROVED** [review]

**Pull request merged**
